### ISSUE TITLE
Man darf doch wohl Issues erstellen, oder?

### ISSUE THREAD

**Issue by jabali2004** [notenverwaltung/Notenverwaltungssoftware#23]
# Grüße vom Seal Team Schreier
![tux](https://user-images.githubusercontent.com/32802935/102553909-f8172980-40c3-11eb-892e-f74776a24ba1.png)

**Comment by tuke307** [comment]
natürlich😛

**Comment by xdavld** [comment]
Entschuldigung, wo liegt das Problem? Ticket wird geschlossen. lol
